# ssh -p 2222 root@localhost
# password: root

services:
  birdclef_app:
    image: bodivencel/birdclef_img:latest # ! Can be used once the image is done and is published on Docker Hub (We hope it is available once we submitted our work)
    # If the image above doesn't work just comment it, download the dataset and build the image.
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: birdclef
    tty: true
    stdin_open: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - QT_X11_NO_MITSHM=1
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "2222:22"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30 --cleanup --label-enable
    restart: always